### PR TITLE
Fix for decimals

### PR DESCRIPTION
**Pull request by edo2313**

### CODE REVIEW

**Comment by edo2313** [comment]
@prickle Please see this PR instead of the other one, sometimes I make mistakes using GitHub 😅

**Comment by prickle** [comment]
Sorry, see the notes in the other thread. I have to head out now, but keep up the great work! I'll be back in a few hours. Cheers!

**Comment by prickle** [comment]
Ok, see how that goes..

**Comment by prickle** [comment]
@edo-2313 if there has been no further issues in regards to decimal translations I will pull this in tomorrow and make a new release. How would you like to be credited in the release notes?

**Comment by edo2313** [comment]
Hi, I have been busy in the past few days so I hadn't much time to test everyhting. As far as I can see the program works well now, I think you could release it! About the credits... It doesn't matter, if you want just put my tag in the notes and that's it 😊

**Comment by prickle** [comment]
Good to hear! Thanks for your valuable help @edo-2313. I am delighted how well this has come together.

Cheers!

**Pull request merged**
