### PR TITLE
Temporary fix for Windows 10

### PR DESCRIPTION
**Pull request by edo2313**
I found out that this line is causing the crash on windows 10. I'll see if I can fix it, but for now just comment it and it works fine.

### CODE REVIEW

**Comment by prickle** [comment]
Hi @edo-2313 .
Thanks for taking a look. Great job finding the crash! 

That's unexpected, why would System.Version() fail? Commenting out the versioning line as you do in your pull request will overcome the crash no doubt, but will also permanently disable firmware update checking. Better to fix it properly perhaps.

If necessary one could rework that section to avoid using System.Version() but there should be no need. Perhaps I am just using System.Version() a bit wrong. Is it possible to provide the details of the exception?
Cheers!

**Comment by edo2313** [comment]
Hi @prickle. I've searched online and did some testing and I found the problem. That line of code causes an ArgumentException because the version variable is something like "21". To make a Version object you need at least two parameters and a maximum of four. When you create the MavpixelVersion object you pass only "21" so it raises the exception. If I add a ".0" by using **MavpixelVersion = new Version(mavpixelVersion+"."+"0");** it works perfectly. I'll see what i can do about it!

**Comment by prickle** [comment]
Interesting. I just confirmed the expected behavior here..
```c++
private void updateTitle(float version)
        {
            if (version <= 0)
            {
                mavpixelVersion = "";
                MavpixelVersion = null;
            }
            else
            {
                mavpixelVersion = version.ToString("F1");
                MavpixelVersion = new Version(mavpixelVersion);
            }
            updateTitle();
        }
```
Version should arrive as a floating point value, in this instance 2.1.  This gets converted to a string, ideally "2.1" and is stored in mavpixelVersion. This gets used with the Version class constructor to make a Version object in MavpixelVersion. The code then goes on to use this info in the window's title bar.

Of course, it all works well here on Win 7, perhaps we could narrow down where is it going wrong for you? 

Is the floating point value coming in as 21, not 2.1? Maybe the version.ToString("F1") (Floating point, 1 decimal place) is converting wrong, i.e is mavpixelVersion not "2.1"?

Just as a wild guess, let's try replacing the line:
```c++
                MavpixelVersion = new Version(mavpixelVersion);
```
with:
```c++
                MavpixelVersion = new Version((int)version, (int)(version * 10) % 10);
```
and see if the error goes away. I doubt this will work but if it does check if the reported version in the title bar is correct.
Let me know how you go. Cheers!

**Comment by edo2313** [comment]
So, I actually tried that a couple of hours ago and if I print to console the value of the variable "version" (which should be 2.1) it actually is 21

The problem isn't in the toString conversion, it's in the value itself that arrives into that function. Do you know if there is a way to analyze the mavlink packets coming from the Arduino? Maybe it's sending the version in a wrong format...

**Comment by prickle** [comment]
Yes, there is a way I am about to describe but note the communication is not via Mavlink right here. Because we are directly connected the gui is in CLI mode which executes commands on the Mavpixel as if they were typed into the CLI. 

At this stage the gui has got the LEDs and Mode Colors and is querying all the current Settings on the newly-connected Mavpixel by sending CLI commands without parameters.

Please try this: put a breakpoint at line 716 of frmPixSettings.cs,
```C#
      if (e.Data.Contains("Unknown")) return; //Fail silently
 ```
and run the program and connect to Mavpixel. When the breakpoint triggers, examine e.Data. The first data value that arrives from Mavpixel should contain "version\r\nVersion: 2.1\r\n#" (which is the sent command followed by Mavpixel's response followed by the prompt). If this is correct, single step over the next line:
```C#
      string txt = e.Data.Split(':')[1].Split(' ')[1].Split('\r')[0];
```
and confirm txt now contains "2.1". Perhaps this somewhat clumsy line of code may be to blame?

If however Mavpixel is not even returning the right version (i.e "version\r\nVersion: 21\r\n#") then please try connecting directly to Mavpixel using your favorite serial terminal. Press enter three times then type "version" and see if it says 2.1 or 21.

I really appreciate your help with this. Debugging this way is not easy.
Cheers!

**Comment by edo2313** [comment]
OK, so i just tried it and txt actually contains 2.1. I'm currently searching where the value loses the point, I think there's a problem when storing the values

**Comment by edo2313** [comment]
Oh ok, found a BIG problem. 
immagine
As you can see, when it crashes the array with all the parameters (which is **params**) is a bit... **strange** I would say 😅
Any clues?

**Comment by prickle** [comment]
No, that's expected. Version at the top is the first param fetched (21, incorrect) and it crashed before anything else was parsed or stored, so all other values are zero. Good thinking though.

So, txt (at line 717, frmPixSettings.cs) contains "2.1" you say.. interesting. Let me look.

Ok, try examining this block of code further down, line 731:
```c#
           else if (float.TryParse(txt, out value))
            {
                storedParams.load(e.Index, value);
                success = true;
            }
```
That float.TryParse(txt, out value) should take the "2.1" in txt and turn it into decimal 2.1 in the value variable. This is the only place it could go wrong that I can see, but just how is not clear to me. Could you please confirm for me this statement is where the decimal point is disappearing, before the value is stored?
Cheers!

**Comment by edo2313** [comment]
I think I've found the problem... It seems to be related to the language of the OS... Based on the documentation of Single.TryParse (or float.TryParse, it's the same) i've added the other 2 parameters:
https://msdn.microsoft.com/it-it/library/0xh24xh4(v=vs.110).aspx

Here in Italy we use the "," instead of the "." to write decimals, so the system expects to see a "," to separate the decimal numbers... I'll see if I can fix this 😄

**Comment by edo2313** [comment]
Yay, fixed it! please do not merge the commit before this message, it was wrongly pushed. I'll open another Pull request with the correct one

**Comment by prickle** [comment]
I guess you changed line 717 to this:
```c#
            else if (float.TryParse(txt, NumberStyles.Float | NumberStyles.AllowDecimalPoint, new CultureInfo("en-US"), out value))
```
Nice one! We also need to change another line, see below at line 764, to be the same.

Great catch!

**Comment by prickle** [comment]
Great work finding this bug @edo-2313 ! I confess not having paid much attention to localization. 

There are other parts of the code where I use float.TryParse but a brief look seems to suggest that because they both are working with the contents of numeric textboxes which should be localized they might work as is.

Have a tinker with the settings dialog and make sure everything is changing and updating properly.
Cheers!

**Comment by prickle** [comment]
Here we go, here's another one..
Line 699:
```c#
                return command + f.ToString(new CultureInfo("en-US"));
```
Plug that in to make Low Cell changes update properly.
There's sure to be more..

**Pull request closed without merging**
